// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

module.exports = sidebars;


// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Manual sidebar definition for primary grades
  tutorialSidebar: [
    // Grade 1
    {type: 'category', label: '1º Primaria', items: [
      '1pri/ut01-placeholder/UT01',
      '1pri/ut02-placeholder/UT02',
      '1pri/ut03-placeholder/UT03',
      '1pri/ut04-placeholder/UT04',
      '1pri/ut05-placeholder/UT05',
      '1pri/ut06-placeholder/UT06',
      '1pri/ut07-placeholder/UT07',
      '1pri/ut08-placeholder/UT08',
      '1pri/ut09-placeholder/UT09',
    ]},
    // Grade 2
    {type: 'category', label: '2º Primaria', items: [
      '2pri/ut01-placeholder/UT01',
      '2pri/ut02-placeholder/UT02',
      '2pri/ut03-placeholder/UT03',
      '2pri/ut04-placeholder/UT04',
      '2pri/ut05-placeholder/UT05',
      '2pri/ut06-placeholder/UT06',
      '2pri/ut07-placeholder/UT07',
      '2pri/ut08-placeholder/UT08',
      '2pri/ut09-placeholder/UT09',
    ]},
    // Grade 3
    {type: 'category', label: '3º Primaria', items: [
      '3pri/ut01-placeholder/UT01',
      '3pri/ut02-placeholder/UT02',
      '3pri/ut03-placeholder/UT03',
      '3pri/ut04-placeholder/UT04',
      '3pri/ut05-placeholder/UT05',
      '3pri/ut06-placeholder/UT06',
      '3pri/ut07-placeholder/UT07',
      '3pri/ut08-placeholder/UT08',
      '3pri/ut09-placeholder/UT09',
    ]},
    // Grade 4
    {type: 'category', label: '4º Primaria', items: [
      '4pri/ut01-placeholder/UT01',
      '4pri/ut02-placeholder/UT02',
      '4pri/ut03-placeholder/UT03',
      '4pri/ut04-placeholder/UT04',
      '4pri/ut05-placeholder/UT05',
      '4pri/ut06-placeholder/UT06',
      '4pri/ut07-placeholder/UT07',
      '4pri/ut08-placeholder/UT08',
      '4pri/ut09-placeholder/UT09',
    ]},
    // Grade 5
    {type: 'category', label: '5º Primaria', items: [
      '5pri/ut01-placeholder/UT01',
      '5pri/ut02-placeholder/UT02',
      '5pri/ut03-placeholder/UT03',
      '5pri/ut04-placeholder/UT04',
      '5pri/ut05-placeholder/UT05',
      '5pri/ut06-placeholder/UT06',
      '5pri/ut07-placeholder/UT07',
      '5pri/ut08-placeholder/UT08',
      '5pri/ut09-placeholder/UT09',
    ]},
    // Grade 6
    {type: 'category', label: '6º Primaria', items: [
      '6pri/ut01-placeholder/UT01',
      '6pri/ut02-placeholder/UT02',
      '6pri/ut03-placeholder/UT03',
      '6pri/ut04-placeholder/UT04',
      '6pri/ut05-placeholder/UT05',
      '6pri/ut06-placeholder/UT06',
      '6pri/ut07-placeholder/UT07',
      '6pri/ut08-placeholder/UT08',
      '6pri/ut09-placeholder/UT09',
    ]},
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
